services:
  pg:
    image: postgres:16-alpine
    restart: always
    ports:
      - "10000:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hospital
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
