// DO NOT EDIT
// This file is autogenerated
// use `pnpm codegen` to update
// If you want to make changes, edit the file scripts/generate-types.ts

// exporting scalars
export * from './scalars/Decimal'

// exporting inputs
export * from './inputs/FilterInputs'

// exporting objects
export * from './objects/Building'
export * from './objects/City'
export * from './objects/Country'
export * from './objects/Facility'
export * from './objects/Organization'
export * from './objects/Person'
export * from './objects/Reservation'
export * from './objects/Residence'
export * from './objects/Resident'
export * from './objects/Staff'
export * from './objects/State'
export * from './objects/Patient'

// exporting queries
export * from './queries/city/list'
export * from './queries/residence/list'
export * from './queries/residence/root'
export * from './queries/resident/list'
export * from './queries/resident/root'

// exporting mutations
export * from './mutations/auth/login'
export * from './mutations/auth/refresh'
export * from './mutations/auth/root'
export * from './mutations/reservation/create'
export * from './mutations/reservation/root'
export * from './mutations/reservation/types'
export * from './mutations/reservation/update'
export * from './mutations/residence/create'
export * from './mutations/residence/root'
export * from './mutations/residence/types'
export * from './mutations/residence/update'
export * from './mutations/patient/create'
export * from './mutations/patient/root'
export * from './mutations/patient/types'
export * from './mutations/patient/update'
export * from './mutations/vehicle/create'
export * from './mutations/vehicle/root'
export * from './mutations/vehicle/types'
export * from './mutations/vehicle/update'
