// DO NOT EDIT
// This file is autogenerated
// use `pnpm generate` to update
// If you want to make changes, edit the file scripts/generate.ts

// exporting tables
export * from './tables/actor'
export * from './tables/emailAddress'
export * from './tables/patient'
export * from './tables/patientEmailAddress'
export * from './tables/patientPhoneNumber'
export * from './tables/person'
export * from './tables/phoneNumber'
export * from './tables/staff'
export * from './tables/user'

// exporting relations
